#!/bin/sh
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
  echo "🚫 Direct pushes to 'main' are not allowed!"
  exit 1
fi

# Copy this file to .git/hooks/pre-push
# Give chmod +x hooks/pre-push to make it executable