name: CI and Code Quality

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901ebb512b2e29a90e7a2637d3612f7263
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@b36c23c0d998641eff861008f2f2019f25eea465
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@1bd1e32a3bdc2024cc2972658b11e1f8c4bebc4c
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with coverage
        run: mvn clean test

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@8885022ab8f48b21a3b5d31397caecd0473db310
        if: always()
        with:
          files: target/surefire-reports/*.xml

      - name: Upload test artifacts
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b312241f0ee72d8d5
        if: always()
        with:
          name: test-results
          path: target/surefire-reports/
          retention-days: 30

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901ebb512b2e29a90e7a2637d3612f7263

      - name: Set up JDK 25
        uses: actions/setup-java@b36c23c0d998641eff861008f2f2019f25eea465
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Checkstyle analysis
        run: mvn checkstyle:check

      - name: Upload Checkstyle results
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b312241f0ee72d8d5
        if: always()
        with:
          name: checkstyle-results
          path: target/checkstyle-result.xml
          retention-days: 7

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901ebb512b2e29a90e7a2637d3612f7263
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@b36c23c0d998641eff861008f2f2019f25eea465
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@1bd1e32a3bdc2024cc2972658b11e1f8c4bebc4c
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@1bd1e32a3bdc2024cc2972658b11e1f8c4bebc4c
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lnchariadoni_JavaLearning